### PR TITLE
Add missing read_hlet_wcs function

### PR DESCRIPTION
**Pull request by stsci-hack**
The missing function has been added into the process.py module.

### CODE REVIEW

**Comment by stscicrawford** [comment]
That fixes this problem,  but it now produces an error on the next line `wcslin = utils.output_wcs(wcslist)`
```
unsupported operand type(s) for /: 'NoneType' and 'float': TypeError
Traceback (most recent call last):
  File "/var/task/process.py", line 1092, in handler
    apply_shifts(event)
  File "/var/task/process.py", line 1056, in apply_shifts
    deltaRA=deltaRA, deltaDEC=deltaDEC)
  File "/var/task/process.py", line 196, in shift_exposure
    expwcs = build_self_reference(hdulist)
  File "/var/task/process.py", line 144, in build_self_reference
    wcslin = utils.output_wcs(wcslist)
  File "/var/task/stwcs/distortion/utils.py", line 44, in output_wcs
    outwcs = make_orthogonal_cd(ref_wcs)
  File "/var/task/stwcs/distortion/utils.py", line 126, in make_orthogonal_cd
    scale = (wcs.idcscale) / 3600.  # HST pixel scale provided
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by stsci-hack** [comment]
This does not make any sense, as I am not able to reproduce the error interactively using this same code (outside of process.py).  I have to wonder, therefore, what input we are really getting from the AWS cache.  
The latest commit (4fe74c5) should provide information which hopefully can be used to understand the cause of the error.

**Comment by stscicrawford** [comment]
I was just trying to reproduce it locally as well but accidentally ran it for a different image (and got a new error), so this might be image dependent.  I'll try both again and post the results with the updated code.

**Comment by stscicrawford** [comment]
Here was the error and full command I was running:

> docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 process.handler '{"s3_output_bucket": "dsmo-lambda-test-outputs", "fits_s3_key":"hst/public/icsc/icsca0voq/icsca0voq_drz.fits", "fits_s3_bucket":"stpubdata"}'
START RequestId: 227fa61d-3773-40ae-8250-ed4af104abbb Version: $LATEST
/var/task/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to FileNotFoundError:2 on None
  warn(ConfigurationMissingWarning(msg))
dsmo-lambda-test-outputs
hst/public/icsc/icsca0voq/icsca0voq_drz.fits
stpubdata
https://gsss.stsci.edu/webservices/GSCconvert/GSCconvert.aspx?TRANSFORM=GSC2-GAIA&IPPPSSOOT=icsca0voq
b'<?xml version="1.0" encoding="utf-8"?>\r\n<ReferenceUpdate observationID="icsca0voq">\r\n  <name>GS</name>\r\n  <inputCatalog>GSC23</inputCatalog>\r\n  <outputCatalog>GSC240</outputCatalog>\r\n  <dGS>N70H000041</dGS>\r\n  <dGSinputRA>177.21310885</dGSinputRA>\r\n  <dGSinputDEC>22.25762389</dGSinputDEC>\r\n  <dGSinputEpoch>2014.97802734</dGSinputEpoch>\r\n  <dGSoutputRA>177.21297245</dGSoutputRA>\r\n  <dGSoutputDEC>22.25765344</dGSoutputDEC>\r\n  <dGSoutputEpoch>2014.97808200</dGSoutputEpoch>\r\n  <dGSraCorrection>-0.00013640</dGSraCorrection>\r\n  <dGSdecCorrection>0.00002955</dGSdecCorrection>\r\n  <dGSxiCorrection>-0.45446574</dGSxiCorrection>\r\n  <dGSetaCorrection>0.10637074</dGSetaCorrection>\r\n  <sGS>NONE</sGS>\r\n  <sGSinputRA>0.00000000</sGSinputRA>\r\n  <sGSinputDEC>0.00000000</sGSinputDEC>\r\n  <sGSinputEpoch>0.00000000</sGSinputEpoch>\r\n  <sGSoutputRA>0.00000000</sGSoutputRA>\r\n  <sGSoutputDEC>0.00000000</sGSoutputDEC>\r\n  <sGSoutputEpoch>0.00000000</sGSoutputEpoch>\r\n  <sGSraCorrection>0.00000000</sGSraCorrection>\r\n  <sGSdecCorrection>0.00000000</sGSdecCorrection>\r\n  <sGSxiCorrection>0.00000000</sGSxiCorrection>\r\n  <sGSetaCorrection>0.00000000</sGSetaCorrection>\r\n  <inputSep>0.00000000</inputSep>\r\n  <inputPA>0.00000000</inputPA>\r\n  <outputSep>0.00000000</outputSep>\r\n  <outputPA>0.00000000</outputPA>\r\n  <FGSlock>FINE/GYRO</FGSlock>\r\n  <RefFrame>ICRS</RefFrame>\r\n  <MTflag>\r\n  </MTflag>\r\n  <deltaRA>-0.00013640</deltaRA>\r\n  <deltaDEC>0.00002955</deltaDEC>\r\n  <deltaXI>-0.45446574</deltaXI>\r\n  <deltaETA>0.10637074</deltaETA>\r\n  <deltaROT>0.00000000</deltaROT>\r\n  <deltaSCALE>0.00000000</deltaSCALE>\r\n  <Nstars>2</Nstars>\r\n  <status>200</status>\r\n  <msg>Success : Dgstar (N70H000041) correction applied</msg>\r\n</ReferenceUpdate>'
Calling shift_exposure for: icsca0voq
wcslist.wcsname: DRZWCS
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 177.4006907390599  22.40512789321821  
CRPIX : 542.0  479.5  
CD1_1 CD1_2  : 3.25450333696595e-05  1.44900477774284e-05  
CD2_1 CD2_2  : 1.44900477774284e-05  -3.2545033369659e-05  
NAXIS : 1084  959
unsupported operand type(s) for /: 'NoneType' and 'float': TypeError
Traceback (most recent call last):
  File "/var/task/process.py", line 1094, in handler
    apply_shifts(event)
  File "/var/task/process.py", line 1058, in apply_shifts
    deltaRA=deltaRA, deltaDEC=deltaDEC)
  File "/var/task/process.py", line 198, in shift_exposure
    expwcs = build_self_reference(hdulist)
  File "/var/task/process.py", line 146, in build_self_reference
    wcslin = utils.output_wcs(wcslist)
  File "/var/task/stwcs/distortion/utils.py", line 44, in output_wcs
    outwcs = make_orthogonal_cd(ref_wcs)
  File "/var/task/stwcs/distortion/utils.py", line 126, in make_orthogonal_cd
    scale = (wcs.idcscale) / 3600.  # HST pixel scale provided
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

END RequestId: 227fa61d-3773-40ae-8250-ed4af104abbb
REPORT RequestId: 227fa61d-3773-40ae-8250-ed4af104abbb Duration: 7384 ms Billed Duration: 7400 ms Memory Size: 1536 MB Max Memory Used: 77 MB

{"errorMessage": "unsupported operand type(s) for /: 'NoneType' and 'float'", "errorType": "TypeError", "stackTrace": [["/var/task/process.py", 1094, "handler", "apply_shifts(event)"], ["/var/task/process.py", 1058, "apply_shifts", "deltaRA=deltaRA, deltaDEC=deltaDEC)"], ["/var/task/process.py", 198, "shift_exposure", "expwcs = build_self_reference(hdulist)"], ["/var/task/process.py", 146, "build_self_reference", "wcslin = utils.output_wcs(wcslist)"], ["/var/task/stwcs/distortion/utils.py", 44, "output_wcs", "outwcs = make_orthogonal_cd(ref_wcs)"], ["/var/task/stwcs/distortion/utils.py", 126, "make_orthogonal_cd", "scale = (wcs.idcscale) / 3600.  # HST pixel scale provided"]]}

**Comment by stsci-hack** [comment]
This code was never meant to be run on drizzled calibrated products (*_drz.fits/*_drc.fits).  This correction only applies to the calibrated, distorted files with _flt/_flc extension.  Arfon's original test run of this code used 'icwb1iu5q_flt.fits' as the input file.  Please try with another FLT/FLC file instead and see what happens.

**Comment by stscicrawford** [comment]
Ah that would be the difference -- I had copied over the command that was in Arfon's instructions and had missed that the file needed to be updated.

**Comment by stsci-hack** [comment]
Let me know if there are any additional issues with this code.  If not, I will merge this PR into master.

**Comment by stscicrawford** [comment]
Ran into one or two other issues -- will submit them as PR

**Comment by stscicrawford** [comment]
Okay, I made one small fix, but now, I don't know the problem that is occurring.  The file name that I'm using is at the top -- but once again, I must have copied this from somewhere, but I'm not sure if I'm using the right file or not. 

```
dsmo-lambda-test-outputs
hst/public/icwb/icwb1iu5q/icwb1iu5q_flt.fits
stpubdata
https://gsss.stsci.edu/webservices/GSCconvert/GSCconvert.aspx?TRANSFORM=GSC2-GAIA&IPPPSSOOT=icwb1iu5q
b'<?xml version="1.0" encoding="utf-8"?>\r\n<ReferenceUpdate observationID="icwb1iu5q">\r\n  <name>GS</name>\r\n  <inputCatalog>GSC23</inputCatalog>\r\n  <outputCatalog>GSC240</outputCatalog>\r\n  <dGS>N6RV000192</dGS>\r\n  <dGSinputRA>153.34925592</dGSinputRA>\r\n  <dGSinputDEC>0.70185626</dGSinputDEC>\r\n  <dGSinputEpoch>2016.14794922</dGSinputEpoch>\r\n  <dGSoutputRA>153.34912091</dGSoutputRA>\r\n  <dGSoutputDEC>0.70187812</dGSoutputDEC>\r\n  <dGSoutputEpoch>2016.14794500</dGSoutputEpoch>\r\n  <dGSraCorrection>-0.00013501</dGSraCorrection>\r\n  <dGSdecCorrection>0.00002187</dGSdecCorrection>\r\n  <dGSxiCorrection>-0.48599793</dGSxiCorrection>\r\n  <dGSetaCorrection>0.07872870</dGSetaCorrection>\r\n  <sGS>NONE</sGS>\r\n  <sGSinputRA>0.00000000</sGSinputRA>\r\n  <sGSinputDEC>0.00000000</sGSinputDEC>\r\n  <sGSinputEpoch>0.00000000</sGSinputEpoch>\r\n  <sGSoutputRA>0.00000000</sGSoutputRA>\r\n  <sGSoutputDEC>0.00000000</sGSoutputDEC>\r\n  <sGSoutputEpoch>0.00000000</sGSoutputEpoch>\r\n  <sGSraCorrection>0.00000000</sGSraCorrection>\r\n  <sGSdecCorrection>0.00000000</sGSdecCorrection>\r\n  <sGSxiCorrection>0.00000000</sGSxiCorrection>\r\n  <sGSetaCorrection>0.00000000</sGSetaCorrection>\r\n  <inputSep>0.00000000</inputSep>\r\n  <inputPA>0.00000000</inputPA>\r\n  <outputSep>0.00000000</outputSep>\r\n  <outputPA>0.00000000</outputPA>\r\n  <FGSlock>\r\n  </FGSlock>\r\n  <RefFrame>ICRS</RefFrame>\r\n  <MTflag>\r\n  </MTflag>\r\n  <deltaRA>-0.00013501</deltaRA>\r\n  <deltaDEC>0.00002187</deltaDEC>\r\n  <deltaXI>-0.48599793</deltaXI>\r\n  <deltaETA>0.07872870</deltaETA>\r\n  <deltaROT>0.00000000</deltaROT>\r\n  <deltaSCALE>0.00000000</deltaSCALE>\r\n  <Nstars>2</Nstars>\r\n  <status>200</status>\r\n  <msg>Success : Dgstar (N6RV000192) correction applied</msg>\r\n</ReferenceUpdate>'
Calling shift_exposure for: icwb1iu5q
wcslist.wcsname: IDC_w3m18525i
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 153.53151672  0.639631557975207  
CRPIX : 507.0  507.0  
CD1_1 CD1_2  : 1.35920466773952e-05  -3.1290063486793e-05  
CD2_1 CD2_2  : -3.5078610992095e-05  -1.2245078361246e-05  
NAXIS : 1014  1014
Coordinate frame  not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']: ValueError
Traceback (most recent call last):
  File "/var/task/process.py", line 1094, in handler
    apply_shifts(event)
  File "/var/task/process.py", line 1058, in apply_shifts
    deltaRA=deltaRA, deltaDEC=deltaDEC)
  File "/var/task/process.py", line 224, in shift_exposure
    unit='deg', frame=wcsframe)
  File "/var/task/astropy/coordinates/sky_coordinate.py", line 208, in __init__
    kwargs = self._parse_inputs(args, kwargs)
  File "/var/task/astropy/coordinates/sky_coordinate.py", line 327, in _parse_inputs
    frame = valid_kwargs['frame'] = _get_frame(args, kwargs)
  File "/var/task/astropy/coordinates/sky_coordinate.py", line 1586, in _get_frame
    frame_cls = _get_frame_class(frame)
  File "/var/task/astropy/coordinates/sky_coordinate.py", line 1528, in _get_frame_class
    .format(frame, sorted(frame_names)))
ValueError: Coordinate frame  not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']

END RequestId: 1d3cc53a-773b-487f-aeed-a1f74586b479
REPORT RequestId: 1d3cc53a-773b-487f-aeed-a1f74586b479 Duration: 8055 ms Billed Duration: 8100 ms Memory Size: 1536 MB Max Memory Used: 77 MB

{"errorMessage": "Coordinate frame  not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']", "errorType": "ValueError", "stackTrace": [["/var/task/process.py", 1094, "handler", "apply_shifts(event)"], ["/var/task/process.py", 1058, "apply_shifts", "deltaRA=deltaRA, deltaDEC=deltaDEC)"], ["/var/task/process.py", 224, "shift_exposure", "unit='deg', frame=wcsframe)"], ["/var/task/astropy/coordinates/sky_coordinate.py", 208, "__init__", "kwargs = self._parse_inputs(args, kwargs)"], ["/var/task/astropy/coordinates/sky_coordinate.py", 327, "_parse_inputs", "frame = valid_kwargs['frame'] = _get_frame(args, kwargs)"], ["/var/task/astropy/coordinates/sky_coordinate.py", 1586, "_get_frame", "frame_cls = _get_frame_class(frame)"], ["/var/task/astropy/coordinates/sky_coordinate.py", 1528, "_get_frame_class", ".format(frame, sorted(frame_names)))"]]}
```

**Comment by stsci-hack** [comment]
This error comes from the observation not having a specified coordinate frame for the WCS specified in the header.  Logic has been added which should insure that the wcsframe always has a valid (non-empty) value, with the default being 'fk5'.

**Comment by stscicrawford** [comment]
Next error -- looks likes wcskey and wscname need to be the same? 

```
dsmo-lambda-test-outputs
hst/public/icwb/icwb1iu5q/icwb1iu5q_flt.fits
stpubdata
https://gsss.stsci.edu/webservices/GSCconvert/GSCconvert.aspx?TRANSFORM=GSC2-GAIA&IPPPSSOOT=icwb1iu5q
b'<?xml version="1.0" encoding="utf-8"?>\r\n<ReferenceUpdate observationID="icwb1iu5q">\r\n  <name>GS</name>\r\n  <inputCatalog>GSC23</inputCatalog>\r\n  <outputCatalog>GSC240</outputCatalog>\r\n  <dGS>N6RV000192</dGS>\r\n  <dGSinputRA>153.34925592</dGSinputRA>\r\n  <dGSinputDEC>0.70185626</dGSinputDEC>\r\n  <dGSinputEpoch>2016.14794922</dGSinputEpoch>\r\n  <dGSoutputRA>153.34912091</dGSoutputRA>\r\n  <dGSoutputDEC>0.70187812</dGSoutputDEC>\r\n  <dGSoutputEpoch>2016.14794500</dGSoutputEpoch>\r\n  <dGSraCorrection>-0.00013501</dGSraCorrection>\r\n  <dGSdecCorrection>0.00002187</dGSdecCorrection>\r\n  <dGSxiCorrection>-0.48599793</dGSxiCorrection>\r\n  <dGSetaCorrection>0.07872870</dGSetaCorrection>\r\n  <sGS>NONE</sGS>\r\n  <sGSinputRA>0.00000000</sGSinputRA>\r\n  <sGSinputDEC>0.00000000</sGSinputDEC>\r\n  <sGSinputEpoch>0.00000000</sGSinputEpoch>\r\n  <sGSoutputRA>0.00000000</sGSoutputRA>\r\n  <sGSoutputDEC>0.00000000</sGSoutputDEC>\r\n  <sGSoutputEpoch>0.00000000</sGSoutputEpoch>\r\n  <sGSraCorrection>0.00000000</sGSraCorrection>\r\n  <sGSdecCorrection>0.00000000</sGSdecCorrection>\r\n  <sGSxiCorrection>0.00000000</sGSxiCorrection>\r\n  <sGSetaCorrection>0.00000000</sGSetaCorrection>\r\n  <inputSep>0.00000000</inputSep>\r\n  <inputPA>0.00000000</inputPA>\r\n  <outputSep>0.00000000</outputSep>\r\n  <outputPA>0.00000000</outputPA>\r\n  <FGSlock>\r\n  </FGSlock>\r\n  <RefFrame>ICRS</RefFrame>\r\n  <MTflag>\r\n  </MTflag>\r\n  <deltaRA>-0.00013501</deltaRA>\r\n  <deltaDEC>0.00002187</deltaDEC>\r\n  <deltaXI>-0.48599793</deltaXI>\r\n  <deltaETA>0.07872870</deltaETA>\r\n  <deltaROT>0.00000000</deltaROT>\r\n  <deltaSCALE>0.00000000</deltaSCALE>\r\n  <Nstars>2</Nstars>\r\n  <status>200</status>\r\n  <msg>Success : Dgstar (N6RV000192) correction applied</msg>\r\n</ReferenceUpdate>'
Calling shift_exposure for: icwb1iu5q
wcslist.wcsname: IDC_w3m18525i
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN-SIP'  'DEC--TAN-SIP'  
CRVAL : 153.53151672  0.639631557975207  
CRPIX : 507.0  507.0  
CD1_1 CD1_2  : 1.35920466773952e-05  -3.1290063486793e-05  
CD2_1 CD2_2  : -3.5078610992095e-05  -1.2245078361246e-05  
NAXIS : 1014  1014
....Updating header for /tmp/icwb1iu5q_flt.fits...
[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x11c810390>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11c8ec5c0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11c8f75c0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11c8fd978>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11c901b70>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11c846c50>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x11c815e10>]
Processing /tmp/icwb1iu5q_flt.fits['SCI',1]
Updating header for /tmp/icwb1iu5q_flt.fits[1]
create_headerlet CRITICAL: 	Inconsistent values for 'wcskey' and 'wcsname' specified!
    'wcskey' =   and 'wcsname' = AWSUpdate. 
Actual value of WCSNAME found to be TWEAK_GAIA_GSC. 

Traceback (most recent call last):
  File "temp.py", line 10, in <module>
    apply_shifts(event)
  File "/Users/scrawford/programs/apriori-astrometry-lambda/process.py", line 1083, in apply_shifts
    hdrlet = headerlet.create_headerlet(im, hdrname=hdrName, wcsname=wcsName, author=author, descrip=descrip, nmatch=nmatch, catalog=catalog)
  File "/Users/scrawford/anaconda3/envs/hla/lib/python3.6/site-packages/stwcs/wcsutil/headerlet.py", line 132, in wrapped
    return func(*args, **kw)
  File "/Users/scrawford/anaconda3/envs/hla/lib/python3.6/site-packages/stwcs/wcsutil/headerlet.py", line 991, in create_headerlet
    raise KeyError
KeyError
```

**Comment by stsci-hack** [comment]
The code which defined the new WCS (shift_exposure) did not use the same 'wcsname' definition as passed into 'create_headerlet'; namely, the value defined as 'wcsName=AWSUpdate' on line 1057.

**Comment by stscicrawford** [comment]
Success!  

```
dsmo-lambda-test-outputs
hst/public/icwb/icwb1iu5q/icwb1iu5q_flt.fits
stpubdata
https://gsss.stsci.edu/webservices/GSCconvert/GSCconvert.aspx?TRANSFORM=GSC2-GAIA&IPPPSSOOT=icwb1iu5q
b'<?xml version="1.0" encoding="utf-8"?>\r\n<ReferenceUpdate observationID="icwb1iu5q">\r\n  <name>GS</name>\r\n  <inputCatalog>GSC23</inputCatalog>\r\n  <outputCatalog>GSC240</outputCatalog>\r\n  <dGS>N6RV000192</dGS>\r\n  <dGSinputRA>153.34925592</dGSinputRA>\r\n  <dGSinputDEC>0.70185626</dGSinputDEC>\r\n  <dGSinputEpoch>2016.14794922</dGSinputEpoch>\r\n  <dGSoutputRA>153.34912091</dGSoutputRA>\r\n  <dGSoutputDEC>0.70187812</dGSoutputDEC>\r\n  <dGSoutputEpoch>2016.14794500</dGSoutputEpoch>\r\n  <dGSraCorrection>-0.00013501</dGSraCorrection>\r\n  <dGSdecCorrection>0.00002187</dGSdecCorrection>\r\n  <dGSxiCorrection>-0.48599793</dGSxiCorrection>\r\n  <dGSetaCorrection>0.07872870</dGSetaCorrection>\r\n  <sGS>NONE</sGS>\r\n  <sGSinputRA>0.00000000</sGSinputRA>\r\n  <sGSinputDEC>0.00000000</sGSinputDEC>\r\n  <sGSinputEpoch>0.00000000</sGSinputEpoch>\r\n  <sGSoutputRA>0.00000000</sGSoutputRA>\r\n  <sGSoutputDEC>0.00000000</sGSoutputDEC>\r\n  <sGSoutputEpoch>0.00000000</sGSoutputEpoch>\r\n  <sGSraCorrection>0.00000000</sGSraCorrection>\r\n  <sGSdecCorrection>0.00000000</sGSdecCorrection>\r\n  <sGSxiCorrection>0.00000000</sGSxiCorrection>\r\n  <sGSetaCorrection>0.00000000</sGSetaCorrection>\r\n  <inputSep>0.00000000</inputSep>\r\n  <inputPA>0.00000000</inputPA>\r\n  <outputSep>0.00000000</outputSep>\r\n  <outputPA>0.00000000</outputPA>\r\n  <FGSlock>\r\n  </FGSlock>\r\n  <RefFrame>ICRS</RefFrame>\r\n  <MTflag>\r\n  </MTflag>\r\n  <deltaRA>-0.00013501</deltaRA>\r\n  <deltaDEC>0.00002187</deltaDEC>\r\n  <deltaXI>-0.48599793</deltaXI>\r\n  <deltaETA>0.07872870</deltaETA>\r\n  <deltaROT>0.00000000</deltaROT>\r\n  <deltaSCALE>0.00000000</deltaSCALE>\r\n  <Nstars>2</Nstars>\r\n  <status>200</status>\r\n  <msg>Success : Dgstar (N6RV000192) correction applied</msg>\r\n</ReferenceUpdate>'
Calling shift_exposure for: icwb1iu5q
....Updating header for /tmp/icwb1iu5q_flt.fits...
[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x11ae0f940>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11af2e550>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11af39550>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11af3d908>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11af42b00>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11aec6be0>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x11ae14da0>]
Processing /tmp/icwb1iu5q_flt.fits['SCI',1]
Updating header for /tmp/icwb1iu5q_flt.fits[1]
```

And a new file name `icwb1iu5q_AWS_hdrlet.fits` was created!

**Pull request merged**
